Repository openshift/lightspeed-operator, pull requests merged in 2024-06, with the labels that each got.

#151 use normal service account to test API endpoint access
  test/e2e/client.go
  test/e2e/tls_test.go
Labels: lgtm, approved

#157 data collector sidecar - raise memory limit to 512MB
  internal/controller/ols_app_server_deployment.go
Labels: lgtm, approved

#159 fix: always update the latest version of CR in e2e reconciliation test
  test/e2e/reconciliation_test.go
Labels: lgtm, approved

#160 OLS-694: Lower collector container resources
  internal/controller/ols_app_server_deployment.go
Labels: jira/valid-reference, lgtm, approved

#154 OLS-644: Use version-aligned OCP docs for RAG
  Makefile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/olsconfig_controller.go
  internal/controller/suite_test.go
Labels: jira/valid-reference, lgtm, approved

#156 [OLS-620] Use all fields from provider secret from the user
  internal/controller/constants.go
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/ols_app_server_reconciliator_test.go
  internal/controller/types.go
  internal/controller/utils.go
Labels: lgtm, approved

#161 Add support for fake llm provider in operator as well
  api/v1alpha1/olsconfig_types.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#150 OLS-579: use MTLS on metric endpoint, replacing kube-rbac-proxy
  bundle/manifests/lightspeed-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lightspeed-operator-controller-manager-service_v1_service.yaml
  bundle/manifests/lightspeed-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor-operator.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/publish_package_builds.sh
  hack/update_bundle_catalog.sh
  internal/controller/constants.go
  internal/controller/olsconfig_controller.go
  test/e2e/http_client.go
  test/e2e/metrics_test.go
  test/e2e/prometheus_client.go
  test/e2e/tls_test.go
Labels: jira/valid-reference, lgtm, approved

#171 add Snyk config to ignore test codes in security check
  .snyk
Labels: lgtm, approved

#169 OLS-499: add data collection settings in OLSConfig CRD.
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
Labels: jira/valid-reference, lgtm, approved

#153 OLS-500: disable data collection when telemetry is off
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  internal/controller/constants.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/olsconfig_controller.go
  internal/controller/resource_watchers.go
  internal/controller/suite_test.go
  internal/controller/utils.go
  lightspeed-catalog/index.yaml
Labels: jira/valid-reference, lgtm, approved

#175 Copy license file into container
  Dockerfile
Labels: lgtm, approved

#181 reenable hermetic builds
  .tekton/lightspeed-operator-pull-request.yaml
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved

#179 Update README.md to include information about other LLMs
  README.md
Labels: lgtm, approved, ok-to-test

#183 OLS-703: Stub for Tekton pipeline for integration tests
  konflux-integration/pipeline.yaml
Labels: jira/valid-reference, lgtm, approved

#192 OLS-702: Konflux integration tests: Info about images to be tested
  konflux-integration/pipeline.yaml
Labels: jira/valid-reference, lgtm, approved

#184 OLS-768: ci/cd: add Konflux pipelines for the bundle component
  .tekton/bundle-pull-request.yaml
  .tekton/bundle-push.yaml
Labels: jira/valid-reference, lgtm, approved

#195 Not restricting the secret to pull-secret as a temp fix
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/olsconfig_controller.go
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#158 Make int32Ptr generic
  test/e2e/autocorrection_test.go
  test/e2e/utils.go
Labels: lgtm, approved
