Repository openshift/lightspeed-operator, pull requests merged in 2024-08, with the labels that each got.

#312 OLS release 0.1.1
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#316 OLS release 0.1.1: snapshot-to-catalog
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
Labels: lgtm, approved

#317 added example for azure openai secret
  README.md
Labels: lgtm, approved

#323 [OLs v0.1.1 ] added upgrade graph with skipRange
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
Labels: lgtm, approved

#324 OLS-514: Add olsconfig to collector sidecar
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
Labels: jira/valid-reference, lgtm, approved

#300 OLS-885: Catalog generation from konflux snapshot
  README.md
  hack/snapshot_to_catalog.sh
Labels: jira/valid-reference, lgtm, approved

#325 [OLS-575] removed disconnect and fips compliant for operator
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#327 refer quay.io images for CI catalog
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#329 OLS release 0.1.2 version update
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#330 OLS 0.1.2: updated image SHAs
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#335 OLS 0.1.2 latest SHAs
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#336 OLS 0.1.2 snapshot ols-fgzk4
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#337 OLS 0.1.2 snapshot-to-catalog with snapshot ols-dlgtp
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#344 OLS 0.1.3 version update
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#348 OLS 0.1.3 latest SHAs
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#349 OLS 0.1.3 snapshot-to-catalog with snapshot ols-cq8sl
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#207 Konflux integration tests introduction
  .tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml
  .tekton/integration-tests/tasks/ols-e2e-task.yaml
  .tekton/integration-tests/tasks/ols-installer.yaml
  .tekton/pull-request.yaml
Labels: lgtm, approved

#328 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/bundle-pull-request.yaml
  .tekton/bundle-push.yaml
  .tekton/lightspeed-operator-pull-request.yaml
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved, ok-to-test

#353 Added skipRange to snapshot_to_catalog.sh
  hack/snapshot_to_catalog.sh
Labels: lgtm, approved

#326 docs: fix wrong name and yaml format
  README.md
Labels: lgtm, approved

#350 OLS 0.1.4 version update
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog/index.yaml
Labels: lgtm, approved

#351 OLS-889 konflux: enable build-source and prefetch dependencies
  .tekton/bundle-push.yaml
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved

#303 OLS-873: Ensure operator configures required OCP and Kubernetes version
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: jira/valid-reference, lgtm, approved

#347 OLS-778, OLS-514: Update data collector configuration
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/types.go
Labels: jira/valid-reference, lgtm, approved

#302 OLS-810: Create option in olsconfig CRD for context_window_size per model
  api/v1alpha1/olsconfig_types.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/types.go
Labels: jira/valid-reference, lgtm, approved

#357 OLS-889 konflux: build-source and prefetch activate for pull requests
  .tekton/bundle-pull-request.yaml
  .tekton/lightspeed-operator-pull-request.yaml
Labels: lgtm, approved

#356 OLS-889 konflux: hermetic build activate on bundle and operator
  .tekton/bundle-pull-request.yaml
  .tekton/bundle-push.yaml
  .tekton/lightspeed-operator-pull-request.yaml
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved

#359 Removed leftover providers and models from the API
  api/v1alpha1/olsconfig_types.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#354 Make image override by each image
  Makefile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
Labels: lgtm, approved

#361 OLS 0.1.4 - updated bundle per snapshot ols-678gh
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
Labels: lgtm, approved

#355 Adding konflux test tasks to pipeline
  .tekton/bundle-pull-request.yaml
  .tekton/integration-tests/pipelines/lightspeed-integration-test-pipeline.yaml
  .tekton/pull-request.yaml
Labels: lgtm, approved

#367 Limiting tests to run on bundle PRs OLS-984
  .tekton/integration-tests/integration-test-scenarios/e2e-tests.yaml
Labels: lgtm, approved
