Repository openshift/lightspeed-operator, pull requests merged in 2025-01, with the labels that each got.

#571 config: fix ignorePaths in renovate config
  renovate.json
Labels: lgtm, approved

#573 OLS-1270: add FIPS-compliant annotation in bundle
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/rbac/role.yaml
  hack/update_bundle.sh
Labels: jira/valid-reference, lgtm, approved

#577 OLS-1029 dependency upgrade
  go.mod
  go.sum
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
Labels: lgtm, approved

#579 config: konflux pipeline updates around related_images.json
  .tekton/bundle-pull-request.yaml
  .tekton/bundle-push.yaml
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved

#581 test: sync testbundle with delivery bundle
  testbundle.Containerfile
Labels: lgtm, approved

#590 Removing imageDigestMirrorSet and removing stage mirror from imageCon…
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
Labels: lgtm, approved

#592 OLS-1333 test: increase prometheus query timeout to 95s
  test/e2e/metrics_test.go
  test/e2e/prometheus_client.go
Labels: lgtm, approved

#564 OLS-1246: the watched namespace becomes configurable
  bundle/manifests/lightspeed-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  cmd/main.go
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor-operator.yaml
  internal/controller/constants.go
  internal/controller/olsconfig_controller.go
  internal/controller/operator_reconciliator.go
  internal/controller/operator_reconciliator_test.go
  test/e2e/metrics_test.go
  test/e2e/rapidast_test.go
Labels: jira/valid-reference, lgtm, approved

#594 OLS-1333 test: increase deployment condition timeout to 15m
  test/e2e/client.go
Labels: lgtm, approved

#597 Added console url to Rapidast Test config
  .tekton/integration-tests/pipelines/rapidast-scan.yaml
  test/e2e/rapidast_test.go
Labels: approved

#596 OLS-1333 test: reduce version conflicts when updating resources
  test/e2e/autocorrection_test.go
Labels: lgtm, approved
