Repository openshift/lightspeed-operator, pull requests merged in 2025-05, with the labels that each got.

#727 Corrected docs links on the operator installation tile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
Labels: lgtm, approved

#721 OLS-1607: Resolve konflux EC failure on service repo - rpm_repos.ids_known
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
  rpms.in.yaml
  rpms.in.yaml.aarch64
  rpms.in.yaml.x86_64
  rpms.lock.yaml
  rpms.lock.yaml.aarch64
  rpms.lock.yaml.x86_64
  ubi.repo
  ubi.repo.x86_64
Labels: jira/valid-reference, lgtm, approved

#714 Adding operator sdk image to test run and removing bundle installatio…
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.15.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.17.yaml
Labels: lgtm, approved

#724 OLS-1333: Fix prometheus metrics test flakyness
  test/e2e/client.go
  test/e2e/metrics_test.go
  test/e2e/prometheus_client.go
Labels: jira/valid-reference, lgtm, approved

#732 conf: operator does not nudge catalog.
  .tekton/lightspeed-operator-push.yaml
Labels: lgtm, approved

#696 OLS-1637 - Adding entraid tests
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
  test/e2e/assets.go
  test/e2e/constants.go
  test/e2e/reconciliation_test.go
Labels: lgtm, approved

#731 OLS-1733 - Adding artifact exporting
  .gitignore
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
  test/e2e/autocorrection_test.go
  test/e2e/constants.go
  test/e2e/metrics_test.go
  test/e2e/rapidast_test.go
  test/e2e/reconciliation_test.go
  test/e2e/suite_test.go
  test/e2e/tls_test.go
  test/e2e/utils.go
Labels: lgtm, approved

#730 OLS-1333: Fix e2e tls_test test flakyness
  test/e2e/client.go
  test/e2e/tls_test.go
Labels: jira/valid-reference, lgtm, approved

#741 Fix for 'go vet' breakage: the cancel function returned by context.WithCancel should be called
  test/e2e/utils.go
Labels: lgtm, approved

#716 OLS-1659: Support token quota in OLSConfig CRD
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  docs/olsconfig-ols-openshift-io-v1alpha1.adoc
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/types.go
Labels: jira/valid-reference, lgtm, approved

#739 OLS-1711: [Operator] Set default MCP config when Introspection is enabled
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/types.go
Labels: jira/valid-reference, lgtm, approved

#728 OLS-1686: OLS should persist postgres data
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/rbac/role.yaml
  docs/olsconfig-ols-openshift-io-v1alpha1.adoc
  internal/controller/constants.go
  internal/controller/errors.go
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_postgres_assets_test.go
  internal/controller/ols_app_postgres_reconciliator.go
  internal/controller/ols_app_postgres_reconciliator_test.go
  internal/controller/olsconfig_controller.go
Labels: jira/valid-reference, lgtm, approved

#744 Revert "added readOnlyRootFilesystem for containers"
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/ols_console_ui_assets.go
Labels: lgtm, approved

#702 OLS-1176: proxy CA configuration
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  internal/controller/constants.go
  internal/controller/errors.go
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/ols_app_server_reconciliator_test.go
  internal/controller/types.go
Labels: jira/valid-reference, lgtm, approved

#743 conf: update related-images with snapshot ols-k95wt
  related_images.json
Labels: lgtm, approved

#745 OLS-1770: Add writable volumes to the operand Deployments to compensate for read-only root fs
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/constants.go
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_postgres_assets_test.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/ols_console_ui_assets.go
Labels: jira/valid-reference, lgtm, approved

#715 OLS-1710: Add artifact gathering and exporting to console tests
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
Labels: jira/valid-reference, lgtm, approved

#751 OLS-1734: conf: disable building image index for bundle as
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
Labels: jira/valid-reference, lgtm, approved

#753 OLS-1734: conf: trigger bundle rebuild for release 0.3.5 with konflux pipeline fixes
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
Labels: jira/valid-reference, lgtm, approved

#755 OLS-1734: conf: FBC update for release 0.3.5
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
Labels: jira/valid-reference, lgtm, approved

#756 OLS-1734 fix: call python3.11 to start MCP servers
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
Labels: lgtm, approved

#738 OLS-1741: Add postgre container memory limit
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_postgres_assets_test.go
Labels: jira/valid-reference, lgtm, approved

#759 OLS-1699 conf: update base image to gotoolset-1.23
  Dockerfile
Labels: lgtm, approved

#762 OLS-1699 bugfix: avoid CI use vendor mode to install go tools
  Makefile
Labels: lgtm, approved

#763 remove test bundle
  testbundle.Containerfile
Labels: lgtm, approved

#761 conf: update konflux build-image-index to resolve EC issue
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/fbc-v4-16-pull-request.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-pull-request.yaml
  .tekton/fbc-v4-17-push.yaml
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
  .tekton/lightspeed-operator-pull-request.yaml
  .tekton/lightspeed-operator-push.yaml
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
Labels: lgtm, approved

#757 OLS-1734: update related images with snapshot ols-pwv4j for release 0.3.5
  related_images.json
Labels: jira/valid-reference, lgtm, approved

#740 OLS-1645: Add lightspeed Konflux pipelines for OCP 4.18
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-418.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-418.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.18.yaml
Labels: jira/valid-reference, lgtm, approved, ok-to-test
