Repository openshift/lightspeed-operator, pull requests merged in 2025-03, with the labels that each got.

#639 OLS-1441 - Adding imagesourcecontent to console tests to be able to run against …
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
Labels: lgtm, approved

#643 updated release 0.3.1 with snapshot ols-lvdfg
  related_images.json
Labels: lgtm, approved

#648 updated related images with snapshot ols-4hs89
  related_images.json
Labels: lgtm, approved

#649 updated the catalog image with -s ols-4hs89 -b ols-bundle-wch9h
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
Labels: lgtm, approved

#650 fbc-fips-check-oci-ta check added
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/fbc-v4-16-pull-request.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-pull-request.yaml
  .tekton/fbc-v4-17-push.yaml
Labels: lgtm, approved

#644 OLS-1489 - Changing run calling to script.
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
Labels: lgtm, approved

#653 Dummy commit to trigger the pipeline
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/fbc-v4-16-pull-request.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-pull-request.yaml
  .tekton/fbc-v4-17-push.yaml
Labels: lgtm, approved

#656 added fips check for bundle
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
Labels: lgtm, approved

#647 Add OCP 4.18 FBC release
  lightspeed-catalog-4.18.Dockerfile
  lightspeed-catalog-4.18/index.yaml
Labels: lgtm, approved

#655 Bump to version 0.3.2
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
Labels: lgtm, approved

#666 add snapshot ols-bsdq2 for bundle
  related_images.json
Labels: lgtm, approved

#665 updated FBC 4.18 pipeline with fips task
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
Labels: lgtm, approved

#669 fixed service image version
  related_images.json
Labels: lgtm, approved

#670 updated catalog files with snapshots ols-bsdq2 and ols-bundle-lhzdl
  bundle.Dockerfile
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
  testbundle.Containerfile
Labels: lgtm, approved

#671 OLS-1471 - Adding tasks to export konflux artifacts
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
Labels: lgtm, approved

#674 Bump to version 0.3.3
  Makefile
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
Labels: lgtm, approved

#385 OLS-449: Operator deploys postgres image
  Makefile
  README.md
  api/v1alpha1/olsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  bundle/manifests/ols.openshift.io_olsconfigs.yaml
  cmd/main.go
  config/crd/bases/ols.openshift.io_olsconfigs.yaml
  config/default/kustomization.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  internal/controller/constants.go
  internal/controller/errors.go
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_postgres_assets_test.go
  internal/controller/ols_app_postgres_reconciliator.go
  internal/controller/ols_app_postgres_reconciliator_test.go
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_deployment.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/olsconfig_controller.go
  internal/controller/suite_test.go
  internal/controller/types.go
  internal/controller/utils.go
  test/e2e/assets.go
  test/e2e/prometheus_client.go
Labels: jira/valid-reference, lgtm, approved, ok-to-test

#641 OLS-1413: catalog removes OKE as valid subscription
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
Labels: jira/valid-reference, lgtm, approved

#654 OLS-1449: bugfix: gracefully handle missing apitoken key in the LLM provider secret
  internal/controller/errors.go
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/ols_app_server_reconciliator_test.go
  internal/controller/olsconfig_controller.go
Labels: jira/valid-reference, lgtm, approved

#677 update related_images.json for release 0.3.3
  related_images.json
Labels: lgtm, approved
