Repository openshift/lightspeed-operator, pull requests merged in 2025-04, with the labels that each got.

#684 conf: FBC update - release 0.3.3
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
  related_images.json
Labels: lgtm, approved

#685 config: EC check fix, add 2 new tasks
  .tekton/fbc-v4-15-pull-request.yaml
  .tekton/fbc-v4-15-push.yaml
  .tekton/fbc-v4-16-pull-request.yaml
  .tekton/fbc-v4-16-push.yaml
  .tekton/fbc-v4-17-pull-request.yaml
  .tekton/fbc-v4-17-push.yaml
  .tekton/fbc-v4-18-pull-request.yaml
  .tekton/fbc-v4-18-push.yaml
  .tekton/lightspeed-operator-pull-request.yaml
  .tekton/lightspeed-operator-push.yaml
  .tekton/ols-bundle-pull-request.yaml
  .tekton/ols-bundle-push.yaml
Labels: lgtm, approved

#689 OLS-1630: fix - api token check for AzureOpenAI provider
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_reconciliator_test.go
Labels: jira/valid-reference, lgtm, approved

#686 Adding step to fail when a step has failed previously
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-complete-e2e-tests-pipeline-417.yaml
Labels: lgtm, approved

#694 fix: PostgreSQL settings have display name and descriptions generated in CSV + kubebuilder tag for permission
  api/v1alpha1/olsconfig_types.go
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/olsconfig_controller.go
Labels: lgtm, approved

#693 OLS-1619: konflux: Split e2e pipelines for service and operator
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-operator-e2e-test-pipeline-417.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.15.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.16.yaml
  .tekton/integration-tests/pipelines/lightspeed-service-integration-test-pipeline-4.17.yaml
Labels: jira/valid-reference, lgtm, approved, ok-to-test

#688 OLS-913: Document all the config options user has in OLSConfig CR
  docs/generating-asciidoc-api.md
  docs/olsconfig-ols-openshift-io-v1alpha1.adoc
  hack/asciidoc-gen-config.yaml
  hack/asciidoc-gen.sh
Labels: jira/valid-reference, lgtm, approved

#701 restricted rbac for secret and clusterrole/bindings
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/olsconfig_controller.go
Labels: lgtm, approved

#698 OLS-1551: add NetworkPolicy limiting ingress traffic.
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/constants.go
  internal/controller/errors.go
  internal/controller/ols_app_postgres_assets.go
  internal/controller/ols_app_postgres_assets_test.go
  internal/controller/ols_app_postgres_reconciliator.go
  internal/controller/ols_app_postgres_reconciliator_test.go
  internal/controller/ols_app_server_assets.go
  internal/controller/ols_app_server_assets_test.go
  internal/controller/ols_app_server_reconciliator.go
  internal/controller/ols_app_server_reconciliator_test.go
  internal/controller/ols_console_reconciliator.go
  internal/controller/ols_console_reconciliator_test.go
  internal/controller/ols_console_ui_assets.go
  internal/controller/ols_console_ui_assets_test.go
  internal/controller/olsconfig_controller.go
  internal/controller/operator_reconciliator.go
  internal/controller/operator_reconciliator_test.go
  internal/controller/utils.go
Labels: jira/valid-reference, lgtm, approved

#703 OLS-1643: Bump to version 0.3.4
  bundle.Dockerfile
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  hack/update_bundle_catalog.sh
Labels: jira/valid-reference, lgtm, approved

#625 Fix the LLM list markdown in the operator description
  bundle/manifests/lightspeed-operator.clusterserviceversion.yaml
  config/manifests/bases/lightspeed-operator.clusterserviceversion.yaml
  lightspeed-catalog-4.17/index.yaml
Labels: lgtm, approved

#704 create bundle using snapshot ols-q445n
  related_images.json
Labels: lgtm, approved

#712 tool: fix version patches
  hack/version_patches/konflux-release-data.patch
  hack/version_patches/service.patch
Labels: lgtm, approved

#711 Fixing console tests and syncing with console pre-commit version
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
Labels: lgtm, approved

#720 updated console label for networkpolicy
  internal/controller/ols_console_ui_assets.go
  internal/controller/ols_console_ui_assets_test.go
Labels: lgtm, approved

#723 NO_JIRA: Fixing console tests to install using bundle image
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-415.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-416.yaml
  .tekton/integration-tests/pipelines/lightspeed-console-e2e-test-pipeline-417.yaml
Labels: lgtm, approved

#725 OLS-1643: update FBC for release 0.3.4
  lightspeed-catalog-4.15/index.yaml
  lightspeed-catalog-4.16/index.yaml
  lightspeed-catalog-4.17/index.yaml
  lightspeed-catalog-4.18/index.yaml
Labels: jira/valid-reference, lgtm, approved

#726 conf: update related images for bundle 0.3.4
  related_images.json
Labels: lgtm, approved
